site_name: flask-openapi3
site_url: https://luolingchun.github.io/flask-openapi3
site_description: Generate RESTful API and OpenAPI document for your Flask project.
site_author: llc

repo_url: https://github.com/luolingchun/flask-openapi3
repo_name: 'GitHub'

markdown_extensions:
  - admonition
  - toc:
      permalink: ⚓︎
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true


theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo-blue.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
  features:
    - navigation.tracking
    - navigation.top
    #    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share

extra:
  alternate:
    - name: English
      link: ./en/
      lang: en
    - name: 简体中文
      link: ./zh/
      lang: zh

plugins:
  - search
  - mkdocstrings
  - glightbox
  - i18n:
      default_language: en
      default_language_only: false
      languages:
        en: English
        zh: 简体中文
      nav_translations:
        zh:
          Home: 简介
          Quickstart: 快速开始
          OpenAPI: OpenAPI
          # OpenAPI-second: start
          Specification: 规范
          Operation: 路由操作
          Request: 请求
          Response: 响应
          # OpenAPI-second: end
          Example: 示例
          API Reference: API 参考
          LICENSE: 许可
          Changelog: 更新日志


extra_javascript:
  - js/db.js

extra_css:
  - css/img.css

nav:
  - Home: index.md
  - Quickstart: Quickstart.md
  - OpenAPI:
      - Specification: OpenAPI/Specification.md
      - Operation : OpenAPI/Operation.md
      - Request: OpenAPI/Request.md
      - Response: OpenAPI/Response.md
  - Example: Example.md
  - API Reference:
      - _Scaffold: Reference/Scaffold.md
      - OpenAPI: Reference/OpenAPI.md
      - APIBlueprint: Reference/APIBlueprint.md
      - APIView: Reference/APIView.md
      - Model:
          - APISpec: Reference/Model/APISpec.md
          - common: Reference/Model/common.md
          - component: Reference/Model/component.md
          - file: Reference/Model/file.md
          - info: Reference/Model/info.md
          - oauth: Reference/Model/oauth.md
          - path: Reference/Model/path.md
          - security: Reference/Model/security.md
          - tag: Reference/Model/tag.md
          - validation_error: Reference/Model/validation_error.md
  - LICENSE: LICENSE.md
  - Changelog: Changelog.md
  - Contributing: Contributing.md
