site_name: flask-openapi3
site_url: https://luolingchun.github.io/flask-openapi3/
site_description: Generate REST API and OpenAPI documentation for your Flask project.
site_author: llc

repo_url: https://github.com/luolingchun/flask-openapi3
repo_name: 'GitHub'

markdown_extensions:
  - admonition
  - toc:
      permalink: ⚓︎
  - md_in_html
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true


theme:
  name: material
  custom_dir: docs/overrides
  logo: images/logo.svg
  favicon: images/logo-blue.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
  features:
    - navigation.tracking
    - navigation.footer
    - navigation.top
    #    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view
    - toc.follow


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
  - glightbox
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - build: true
          default: true
          locale: en
          name: English
        - build: true
          default: false
          locale: zh
          name: 简体中文
          nav_translations:
              Home: 简介
              Quickstart: 快速开始
              Usage: 教程
              Specification: 规范
              Request: 请求
              Response: 响应
              Route Operation: 路由操作
              Model Config: 模型配置
              UI Templates: 自定义模板
              Example: 示例
              API Reference: API 参考
              LICENSE: 许可
              Changelog: 更新日志
              Contributing: 贡献

extra:
  version:
      provider: mike

extra_javascript:
  - js/db.js

extra_css:
  - css/img.css

nav:
  - Home: index.md
  - Quickstart: Quickstart.md
  - Usage:
      - Specification: Usage/Specification.md
      - Request: Usage/Request.md
      - Response: Usage/Response.md
      - Route Operation: Usage/Route_Operation.md
      - Model Config: Usage/Model_Config.md
      - UI Templates: Usage/UI_Templates.md
      - JSON: Usage/JSON.md
  - Example: Example.md
  - API Reference:
      - APIScaffold: Reference/Scaffold.md
      - OpenAPI: Reference/OpenAPI.md
      - APIBlueprint: Reference/APIBlueprint.md
      - APIView: Reference/APIView.md
      - Models: Reference/Models.md
  - LICENSE: LICENSE.md
  - Changelog: Changelog.md
  - Contributing: Contributing.md
